name: messagingapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  easy_search_bar: ^2.5.0
  email_validator: ^2.1.17
  file_picker: ^5.3.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.2
  sleek_circular_slider: ^2.0.1
  firebase_ui_auth: ^1.4.2
  flutter:
    sdk: flutter
  flutter_chat_list: ^1.0.6
  flutter_chat_ui: ^1.6.8
  flutter_statusbarcolor_ns: ^0.5.0
  google_sign_in: ^6.1.4
  image_picker: ^0.8.8
  photo_view: ^0.14.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
