// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWRnyVNZeo6caNzNm5ceFLTe0OM6m4dg',
    appId: '1:674242066988:web:fcc78f87513948e589ef89',
    messagingSenderId: '674242066988',
    projectId: 'messagingapp-6f1b1',
    authDomain: 'messagingapp-6f1b1.firebaseapp.com',
    storageBucket: 'messagingapp-6f1b1.appspot.com',
    measurementId: 'G-6S53S9RG0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4IJWfTV5ae_gnyrhaLj6fUBGP3fbVxsM',
    appId: '1:674242066988:android:ede2e63eefa679fa89ef89',
    messagingSenderId: '674242066988',
    projectId: 'messagingapp-6f1b1',
    storageBucket: 'messagingapp-6f1b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBq8dL7S8ZG52QdLMwvl5jntPLnpz7Z3Q',
    appId: '1:674242066988:ios:2cdffccb377ede7589ef89',
    messagingSenderId: '674242066988',
    projectId: 'messagingapp-6f1b1',
    storageBucket: 'messagingapp-6f1b1.appspot.com',
    iosClientId: '674242066988-4u8jb08ipcnf6u64nj8uakub0koe78hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBq8dL7S8ZG52QdLMwvl5jntPLnpz7Z3Q',
    appId: '1:674242066988:ios:23b5103373466a6f89ef89',
    messagingSenderId: '674242066988',
    projectId: 'messagingapp-6f1b1',
    storageBucket: 'messagingapp-6f1b1.appspot.com',
    iosClientId: '674242066988-hrdh29p9ieosb4f5de96ur4n9nrb9hqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingapp.RunnerTests',
  );
}
